import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,place,upgrade,sell,startWave,tick,spot,onRoad,pointAt,pathLength,MAPS,wavePlan} from '../public/engine.js';
import {validGame,Player} from '../worker/index.js';
const until=(s,predicate,max=10000)=>{for(let i=0;i<max&&predicate(s);i++)tick(s,.05);return s};
test('all sectors have build sites, reject roads, enforce spending and upgrades',()=>{for(let map=0;map<3;map++){const s=fresh(map);assert.ok(validGame(s));let count=0;for(let c=0;c<10;c++)for(let r=0;r<12;r++){const p=spot(c,r);if(!onRoad(map,p.x,p.y))count++}assert.ok(count>30);assert.equal(place(s,'unknown',0,0),false);let cell;for(let c=0;c<10;c++)for(let r=0;r<12;r++)if(!cell&&!onRoad(map,...Object.values(spot(c,r))))cell=[c,r];assert.equal(place(s,'bolt',...cell),true);assert.equal(s.gold,115);assert.equal(place(s,'bolt',...cell),false);assert.equal(upgrade(s,s.towers[0].id),true);assert.equal(s.towers[0].level,2);assert.ok(validGame(s));assert.equal(sell(s,s.towers[0].id),true);assert.equal(s.towers.length,0)}});
test('undefended core loses and cannot start another wave',()=>{const s=fresh();for(let w=0;w<4&&s.health>0;w++){startWave(s);until(s,s=>s.status==='wave')}assert.equal(s.status,'lost');assert.equal(startWave(s),false);assert.ok(validGame(s))});
test('combat damages enemies, grants rewards once, clears waves and snapshot resumes exactly',()=>{const s=fresh();s.gold=1000;for(const [type,c,r] of [['bolt',2,1],['bolt',4,4],['cannon',2,5],['frost',5,3]])assert.equal(place(s,type,c,r),true);startWave(s);for(let i=0;i<100;i++)tick(s,.05);assert.ok(validGame(s));const clone=structuredClone(s);for(let i=0;i<700;i++){tick(s,.05);tick(clone,.05)}assert.deepEqual(s,clone);until(s,s=>s.status==='wave');assert.equal(s.status,'build');assert.ok(s.kills>0);const gold=s.gold;tick(s,.05);assert.equal(s.gold,gold);assert.ok(validGame(s))});
test('boss waves and scaling',()=>{assert.ok(wavePlan(4,0).some(e=>e.type==='boss'));assert.ok(wavePlan(12,2).at(-1).hp>wavePlan(4,0).at(-1).hp);for(const map of [0,1,2])assert.ok(pathLength(map)>500)});
test('cloud saves serialize revisions and preserve campaign progress',async()=>{const records=new Map(),ctx={storage:{get:async k=>structuredClone(records.get(k)),put:async(k,v)=>records.set(k,structuredClone(v))}},p=new Player(ctx);const get=()=>p.fetch(new Request('https://test/api/a'));let state=await(await get()).json();const save=(g,v=state.version)=>p.fetch(new Request('https://test/api/a',{method:'POST',body:JSON.stringify({version:v,game:g})}));assert.equal((await save(fresh(1))).status,403);const responses=await Promise.all([save(fresh()),save(fresh())]);assert.deepEqual(responses.map(r=>r.status),[200,409]);state=await(await get()).json();assert.equal((await save({...fresh(),health:-1})).status,400);const won=fresh();won.wave=12;won.status='won';state=await(await save(won)).json();assert.equal(state.unlocked,1);assert.equal(state.best[0],12);const restored=new Player(ctx);assert.equal((await(await restored.fetch(new Request('https://test/api/a'))).json()).unlocked,1)});
