import vm from 'node:vm';import fs from 'node:fs';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import * as engine from '../public/engine.js';import {validGame} from '../worker/index.js';
const require=createRequire(import.meta.url),{createCanvas}=require('@napi-rs/canvas');
class Element{constructor(id){this.id=id;this.hidden=false;this.children=[];this.style={};this.dataset={};this.clientWidth=360;this.clientHeight=432;this.events={};this.classList={toggle(){}};this.disabled=false;this.value='test'}addEventListener(name,fn){this.events[name]=fn}setAttribute(){}replaceChildren(){this.children=[]}append(...n){this.children.push(...n)}showModal(){this.open=true}close(){this.open=false}click(){this.onclick?.()}getBoundingClientRect(){return {left:0,top:0,width:360,height:432}}}
const els=new Map(),$=id=>{if(!els.has(id))els.set(id,new Element(id));return els.get(id)};
$('banner').hidden=true;
const field=createCanvas(720,864);field.style={};field.events={};field.addEventListener=(name,fn)=>field.events[name]=fn;field.getBoundingClientRect=()=>({left:0,top:0,width:360,height:432});els.set('field',field);
const cards=['bolt','cannon','frost'].map(type=>Object.assign(new Element(type),{dataset:{tower:type}})),storage=new Map();let saved={version:0,unlocked:0,best:[0,0,0],game:null};
const sandbox={...engine,document:{getElementById:$,querySelectorAll:()=>cards,createElement:()=>new Element(),hidden:false,activeElement:null,addEventListener(){}},location:{pathname:'/test',origin:'https://test',reload(){}},navigator:{clipboard:{writeText:async()=>{}}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},matchMedia:()=>({matches:false}),performance:{now:()=>5000},devicePixelRatio:2,ResizeObserver:class{constructor(fn){this.fn=fn}observe(){this.fn()}},window:{addEventListener(){}},requestAnimationFrame(){},setInterval(){},setTimeout,clearTimeout,queueMicrotask,structuredClone,AbortSignal,console,confirm:()=>true,prompt(){},fetch:async(url,options)=>{if(options?.body){const b=JSON.parse(options.body);assert.ok(validGame(b.game));saved={...saved,version:saved.version+1,game:b.game};}return {ok:true,status:200,json:async()=>structuredClone(saved)}}};
const context=vm.createContext(sandbox);vm.runInContext(fs.readFileSync(new URL('../public/app.js',import.meta.url),'utf8').replace(/^import .*?;\n/,''),context);
await new Promise(r=>setImmediate(r));$('close-help').click();
assert.equal(vm.runInContext('ready',context),true);field.events.pointerup({clientX:270,clientY:18,isPrimary:true});await new Promise(r=>setImmediate(r));assert.equal(vm.runInContext('game.towers.length',context),1);assert.equal(vm.runInContext('game.gold',context),115);
cards[1].click();field.events.pointerup({clientX:90,clientY:198,isPrimary:true});await new Promise(r=>setImmediate(r));assert.equal(vm.runInContext('game.towers.length',context),2);$('launch').click();await new Promise(r=>setImmediate(r));assert.equal(vm.runInContext('game.status',context),'wave');
vm.runInContext('for(let i=0;i<200;i++)tick(game,.05,effects);draw(.016);update()',context);$('pause').click();assert.equal(vm.runInContext('paused',context),true);$('banner-action').click();assert.equal(vm.runInContext('paused',context),false);
// Render the actual Canvas drawing code for visual inspection.
vm.runInContext(`game.gold=1000;for(const [type,c,r] of [['frost',5,3],['cannon',3,7],['bolt',6,10]])place(game,type,c,r);game.enemies=[{lane:0,id:99,type:'boss',d:470,hp:500,maxHp:650,slow:0},{lane:1,id:100,type:'tank',d:245,hp:70,maxHp:100,slow:1},{lane:0,id:101,type:'runner',d:310,hp:20,maxHp:22,slow:0}];draw(.016)`,context);
fs.writeFileSync('/tmp/td-field.png',field.toBuffer('image/png'));
console.log('PASS: app boot, tutorial, tap placement, spending, starting a wave, pause/resume, valid API payloads and actual Canvas rendering.');
